version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTICSEARCH_PASSWORD=jt+1aIMg0V6uLm8X5QO7
      - xpack.security.enabled=true
      # - xpack.security.authc.api_key.enabled=true
      # - xpack.security.http.ssl.enabled=true
      # - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/certs/http.p12
      # - xpack.security.http.ssl.truststore.path=/usr/share/elasticsearch/config/certs/http.p12
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certs
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - "5044:5044"
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=logstash_user
      - ELASTICSEARCH_PASSWORD=logstash_password
    depends_on:
      - elasticsearch
    networks:
      - elk
    platform: linux/arm64
    command: /bin/bash -c "chmod 644 /usr/share/logstash/config/certs/ca.crt && /usr/share/logstash/bin/logstash -f /usr/share/logstash/pipeline/logstash.conf"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_user
      - ELASTICSEARCH_PASSWORD=kibana_password
      - SERVER_HOST=0.0.0.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/usr/share/kibana/config/certs
    depends_on:
      - elasticsearch
    networks:
      - elk
    platform: linux/arm64

volumes:
  elasticsearch_data:
    driver: local

networks:
  elk:
    driver: bridge